### ISSUE TITLE
Maybe make github -> slack mapping explicit always

### ISSUE THREAD

**Issue by matthauck** [tanium/octobot#160]
Currently we guess at slack usernames based on github usernames: "matt-hauck" we guess is "matt.hauck". While this was nice for easy deploying, it is probably not super helpful in the general case and also results in lack of clarity about who is setup for messaging and who is not. Maybe we should remove this.

**Comment by bblancha** [comment]
I agree that making clear who is configured is important, especially for larger groups.

Do you know the ratio of messages sent to manually configured users vs "guessed" users in your deployments?

**Comment by matthauck** [comment]
i imagine the number is probably small... we can figure it out probably.
