### ISSUE TITLE
Octobot doesn't update Jira ticket with fix version when merging into a main branch named `main`

### ISSUE THREAD

**Issue by justfalter** [tanium/octobot#247]
Since renaming `master` to `main`, Octobot stopped setting a fix-version when merging into the branch.
Looking at the [codebase](https://github.com/tanium/octobot/blob/9edd0bb0d0108521a9b35189cde49c7f6cbca514/src/server/github_handler.rs#L633), I can see that `is_main_branch` assumes the main branch to be named `master`, `develop`, or have the release branch prefix. 

My suggestion: add a repo config option for a regular expression that is to be used for matching the main branch of a repository, and have it default to `^(main|master|develop)$`.

**Comment by sean-mize** [comment]
Repo config option with regex would be great! For new [Console workbench](https://git.corp.tanium.com/tanium/console) we named our default branch `default` to line up with GitHub labeling.

**Comment by sean-mize** [comment]
Fixed by https://github.com/tanium/octobot/pull/248?
