### ISSUE TITLE
Add option to configure jira transition to project config

### ISSUE THREAD

**Issue by crazyjaw** [tanium/octobot#82]
Right now there is a octobot has a project setting to enable jira transitions, but once its enable, you are required to add "Fixes JIRA_ID" to get it to actually tranistion the ticket.

For protect, we want to just automatically tranistion PR's ticket, and its awkward to add that "fixes x" bit, since all the PR's have the format "Prot-1234 fixes something..." 

It would be nice if we had the ability to either specify the regex that is used to pick up these transitions, or just have a flag to "always transition" vs "require "Fixed" prefex"

**Comment by matthauck** [comment]
I think this ship has sailed and predictability across projects/repos ended up being more important than flexibility here.
